run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - unused
    - gofmt
    - gocritic
    - revive
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-use-default: false
